repos:
  # Check for secrets using ripsecrets
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.8
    hooks:
      - id: ripsecrets

  # Format files using Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.1.0
    hooks:
      - id: prettier
        args: [--write]
        files: \.[jt]sx?$

  # Lint files using ESLint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.10.0
    hooks:
      - id: eslint
        args: [--fix]
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
