repos:
  # Check for secrets using ripsecrets
  - repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.8
    hooks:
      - id: ripsecrets

  # Lint files using ESLint
  - repo: local
    hooks:
      - id: eslint
        name: eslint (bun)
        entry: bun lint:fix
        language: system
        files: ^src/
